PRODUCT_ID := a6nm
CLASS_ID:=iptime

CPU_NAME:=mt7621
WIFI_2G:=mt7615
WIFI_5G:=mt7615
DRAM_SIZE:=128m

HW_NAT:=y
FLASH_SIZE:=0x1000000
# Because  PCIE0->5G & PCIE1 ->2G
EEPROM_FILE:=IP04318_EEPROM_5.8G.bin
EEPROM_FILE_5G:=IP04318_EEPROM_2.4G.bin
DRAM_SIZE_POSTFIX:=128m
BOOT_FILENAME:=uboot.bin.mt7621.128m.5.0.2.0
USE_FACTORY_SECTION:=y
SQUASHCMD:=./mksquash
SQUASHCMD_COMP:=xz
NO_PADDING_FOR_ROOTFS:=y
LOAD_ADDRESS := 80001000
LANG_PACKS:=kr,en

PRODUCT_TAG:=$(CPU_NAME).$(WIFI_2G).$(WIFI_5G).$(DRAM_SIZE)$(if $(OPTION_TAG),.$(OPTION_TAG))
KERNEL_FILENAME:=vmlinux.$(PRODUCT_TAG)
KCONFIG_FILE_NAME:=config.$(PRODUCT_TAG)
MODULE_DIR:=$(PRODUCT_TAG)
TNTFS_MODULE_NAME:=tntfs.ko.$(PRODUCT_TAG)

SDK_VERSION:=SDK_5020
KERNEL_PATH:=../../linux
PREMAKE_TARGET_NAME:=$(WIFI_2G)

